/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pdlcalculator;

/**
 *
 * @author isaac
 */
public class calculadorapdl extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(calculadorapdl.class.getName());

    /**
     * Creates new form calculadorapdl
     */
    public calculadorapdl() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rbMagro = new javax.swing.JRadioButton();
        rbComum = new javax.swing.JRadioButton();
        rbFalsoMagro = new javax.swing.JRadioButton();
        rbIntermediario = new javax.swing.JRadioButton();
        rbForte = new javax.swing.JRadioButton();
        rbAoPeso = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbMusculacao = new javax.swing.JRadioButton();
        rbArtesM = new javax.swing.JRadioButton();
        rbCardio = new javax.swing.JRadioButton();
        rbCaminha = new javax.swing.JRadioButton();
        rbOutro = new javax.swing.JRadioButton();
        rbSedentas = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        btShow = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CALCULADORA DE PODER DE LUTA");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\isaac\\Documents\\NetBeansProjects\\pdlcalculator\\src\\images\\ki.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(119, 119, 119))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("CORPO:");

        body.add(rbMagro);
        rbMagro.setText("Magro");

        body.add(rbComum);
        rbComum.setText("Comum");

        body.add(rbFalsoMagro);
        rbFalsoMagro.setText("Falso Magro");
        rbFalsoMagro.addActionListener(this::rbFalsoMagroActionPerformed);

        body.add(rbIntermediario);
        rbIntermediario.setText("Intermediário");
        rbIntermediario.addActionListener(this::rbIntermediarioActionPerformed);

        body.add(rbForte);
        rbForte.setText("Forte");
        rbForte.addActionListener(this::rbForteActionPerformed);

        body.add(rbAoPeso);
        rbAoPeso.setText("Acima do Peso");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("EXERCÍCIOS PRATICADOS (pode marcar mais de um):");

        rbMusculacao.setText("Musculação");
        rbMusculacao.addActionListener(this::rbMusculacaoActionPerformed);

        rbArtesM.setText("Artes Marciais");
        rbArtesM.addActionListener(this::rbArtesMActionPerformed);

        rbCardio.setText("Cárdio");
        rbCardio.addActionListener(this::rbCardioActionPerformed);

        rbCaminha.setText("Caminhada");
        rbCaminha.addActionListener(this::rbCaminhaActionPerformed);

        rbOutro.setText("Outro");
        rbOutro.addActionListener(this::rbOutroActionPerformed);

        rbSedentas.setText("Sedentário");
        rbSedentas.addActionListener(this::rbSedentasActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("MÉDIA DE TREINOS POR SEMANA:");

        jTextField1.setBackground(new java.awt.Color(239, 239, 239));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTextField2.setBackground(new java.awt.Color(239, 239, 239));
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("SUA IDADE:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("SEU NOME:");

        jTextField5.setBackground(new java.awt.Color(239, 239, 239));
        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        btShow.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btShow.setText("ME MOSTRE!");
        btShow.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btShow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btShow.addActionListener(this::btShowActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(rbMagro)
                        .addGap(18, 18, 18)
                        .addComponent(rbFalsoMagro)
                        .addGap(18, 18, 18)
                        .addComponent(rbComum)
                        .addGap(18, 18, 18)
                        .addComponent(rbIntermediario)
                        .addGap(18, 18, 18)))
                .addComponent(rbForte)
                .addGap(18, 18, 18)
                .addComponent(rbAoPeso)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(rbMusculacao)
                        .addGap(18, 18, 18)
                        .addComponent(rbArtesM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCardio)
                        .addGap(18, 18, 18)
                        .addComponent(rbCaminha)
                        .addGap(18, 18, 18)
                        .addComponent(rbSedentas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbOutro)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(101, 101, 101))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField5)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(btShow, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMagro)
                    .addComponent(rbFalsoMagro)
                    .addComponent(rbIntermediario)
                    .addComponent(rbForte)
                    .addComponent(rbAoPeso)
                    .addComponent(rbComum))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMusculacao)
                    .addComponent(rbArtesM)
                    .addComponent(rbCardio)
                    .addComponent(rbCaminha)
                    .addComponent(rbOutro)
                    .addComponent(rbSedentas))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(btShow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void rbSedentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSedentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSedentasActionPerformed

    private void rbOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOutroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOutroActionPerformed

    private void rbCaminhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCaminhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCaminhaActionPerformed

    private void rbCardioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCardioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCardioActionPerformed

    private void rbArtesMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbArtesMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbArtesMActionPerformed

    private void rbMusculacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMusculacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMusculacaoActionPerformed

    private void rbForteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbForteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbForteActionPerformed

    private void rbIntermediarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIntermediarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIntermediarioActionPerformed

    private void rbFalsoMagroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFalsoMagroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFalsoMagroActionPerformed
    // TODO add your handling code here:

    private void btShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowActionPerformed
try {
        double forca = 1.0;
        double versatilidade = 1.0;

        // Lógica de Corpo
        if (rbForte.isSelected()) { forca = 1.6; versatilidade = 1.3; }
        else if (rbIntermediario.isSelected()) { forca = 1.5; versatilidade = 1.1; }
        else if (rbFalsoMagro.isSelected()) { forca = 1.2; versatilidade = 1.0; }
        else if (rbComum.isSelected()) { forca = 1.1; versatilidade = 1.0; }
        else if (rbAoPeso.isSelected()) { forca = 1.2; versatilidade = 0.5; }
        else if (rbMagro.isSelected()) { forca = 0.8; versatilidade = 1.6; }

        // Multiplicador de Exercícios
        double multExercicio = 1.0; 
        if (rbSedentas.isSelected()) {
            multExercicio = 0.5;
        } else {
            if (rbMusculacao.isSelected()) multExercicio += 0.5;
            if (rbArtesM.isSelected()) multExercicio += 0.8; 
            if (rbCardio.isSelected()) multExercicio += 0.3;
            if (rbCaminha.isSelected()) multExercicio += 0.1;
            if (rbOutro.isSelected()) multExercicio += 0.2;
        }

        // Pegando os valores das caixas de texto
        String nome = jTextField5.getText();
        int treinos = Integer.parseInt(jTextField1.getText());
        int idade = Integer.parseInt(jTextField2.getText());

        // Cálculo Final
        double poderFinal = (100.0 * ((forca * 0.7) + (versatilidade * 0.3)) * multExercicio) + (treinos * 25);

        // Mostrando o resultado
        String msg = "GUERREIRO: " + nome.toUpperCase() + "\n" + "PODER DE LUTA: " + Math.round(poderFinal);
        javax.swing.JOptionPane.showMessageDialog(this, msg);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Preencha os campos corretamente!");
    }     // TODO add your handling code here:
    }//GEN-LAST:event_btShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new calculadorapdl().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup body;
    private javax.swing.JToggleButton btShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JRadioButton rbAoPeso;
    private javax.swing.JRadioButton rbArtesM;
    private javax.swing.JRadioButton rbCaminha;
    private javax.swing.JRadioButton rbCardio;
    private javax.swing.JRadioButton rbComum;
    private javax.swing.JRadioButton rbFalsoMagro;
    private javax.swing.JRadioButton rbForte;
    private javax.swing.JRadioButton rbIntermediario;
    private javax.swing.JRadioButton rbMagro;
    private javax.swing.JRadioButton rbMusculacao;
    private javax.swing.JRadioButton rbOutro;
    private javax.swing.JRadioButton rbSedentas;
    // End of variables declaration//GEN-END:variables
}
